---
kind: Service
apiVersion: v1
metadata:
  name: rabbitmqservice
spec:
  selector:
    app: rabbitmq
  ports:
    - name: container
      protocol: TCP
      port: 80
      targetPort: 5672
    - name: management
      protocol: TCP
      port: 443
      targetPort: 15672
      nodePort: 30001
  type: LoadBalancer
 
 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmqdeployment
  labels:
    app: rabbitmq
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
        ports:
        - containerPort: 5672
        - containerPort: 15672
 
            
---
kind: Service
apiVersion: v1
metadata:
  name: consumerservice
spec:
  selector:
    app: consumer
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30002
  type: LoadBalancer
 


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumerdeployment
  labels:
    app: consumer
spec:
  replicas: 5
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
      - name: consumer
        image: menfra/consumer
        ports:
        - containerPort: 80
 
            
            
---
kind: Service
apiVersion: v1
metadata:
  name: producerservice
spec:
  selector:
    app: myapp
  ports:
    - protocol: "TCP"
      # Port accessible inside cluster
      port: 8081
      # Port to forward to inside the pod
      targetPort: 8080
      # Port accessible outside cluster
      nodePort: 30003
  type: LoadBalancer
 


---
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: producerdeployment
  labels:
    app: producer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - name: producer
        image: menfra/producer
        ports: 
 